# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170517_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='organization',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='blog.Worker', verbose_name='Руководитель'),
        ),
    ]
