# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170517_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdata',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='orgdata',
            name='user',
        ),
        migrations.AlterField(
            model_name='organization',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief', to='blog.Worker', verbose_name='Руководитель'),
        ),
        migrations.DeleteModel(
            name='orgdata',
        ),
    ]
